= Любимая детская литература 

Здесь я хочу прежде всего поделиться своей любимой детской литературой, которая не всегда занимает первые места на полках книжных и топовые позиции в выдаче интернет-магазинов.

Это не значит, что мы не любим и не читаем Дениса Драгунского или Карлсона и Пеппи-длинный-чулок Линдгрен, Николая Носова и т.д.
Просто в рамках школьной программе ваши дети и так это прочтут.

Основное внимание хочется уделить дополнительной литературе, которую было приятно читать прежде всего самому.

Хотя, сказать по-правде, большую часть книг мы всё-таки читали вместе с детьми (я - с сыном, а жена - с дочкой).
Меньшую - дети читали сами без нашего участия.
И самую малость - мы сами читали в детстве и, может быть, прочтём вместе, если достанем.

Группировать книги буду прежде всего по национальности автора (хотя я и не имею ничего общего с национализмом, разве что мне симпатичен здоровый этноцентризм). Далее, если у автора несколько книг - то и по автору.

Никакого желания обозначать жанр произведения у меня почему-то нет.

Разумеется, существуют так-называемое деление на литературу для мальчишек и девчонок. Может быть, в будущем сделаю какие-нибудь пометки касательно этого признака, но пока просто не хочу на это отвлекаться.

Итак, приступим...

== Русская, Советская, Российская и СНГ-литература

.Наринэ Абгарян
. Шоколадный Дедушка
. Семён Андреевич. Летопись в каракулях

.Дина Сабитова и Алика Калайда
. Мышь Гликерия. Цветные и полосатые Дни

.Александра Бруштейн
. Дорога уходит в даль
. В рассветный час
. Весна

.Юрий Сотник
. Как я был самостоятельным
. "Архимед" Вовки Грушина

.Юрий Яковлев
. Последний Фейерверк

.Юрий Третьяков
. Толстый мальчишка Глеб
. Про Андрейку, Моську, Алёху и Читаку
. Андрейка и лодырь Ромашка

.Дядя Коля Воронцов
. Кот Помпон и маленькие, но гордые птички

.Корней Чуковский
. Серебрянный Герб

.Владислав Крапивин
. ???

.Эдуард Скобелев
. Приключения Арбузика и Бебешки

== Английская литература

.Джеральд Даррелл
. Моя семья и другие звери

== Литература Скандинавских стран

.Альф Прёйсен
. Старушка крошка с чайную ложку

== Немецкая литература

.Андреас Шмахтл
. Изобретатель Иероним

== Прочая литература

.Люси и Стивен Хоккинг
. Джордж и тайны вселенной
. Джордж и сокровища вселенной
. Джордж и большой взрыв
. Джордж и код, который не взломать

.Роальд Даль
. Чарли и шоколадная фабрика

